const Doctor = [
  {
    _id: 1,
    name: "Hazel Pinto",
    specialization: "Dermatologist",
    onlineStatus: "Y",
    age: 45,
    photo:
      "https://m.media-amazon.com/images/M/MV5BMTY1OTk1NzQwOF5BMl5BanBnXkFtZTgwNDUzNTA3NjE@._V1_UY1200_CR135,0,630,1200_AL_.jpg",
    rating: 4.2,
    experience: 12,
    languages: ["English", "Hindi", "Marathi"],
    fees: 600,
  },
  {
    id: 2,
    name: "Abdul Bari",
    specialization: "General Physician",
    onlineStatus: "Y",
    age: 32,
    photo: "https://randomuser.me/api/portraits/men/21.jpg",
    rating: 4.7,
    experience: 8,
    languages: ["English", "Hindi", "Urdu"],
    fees: 300,
  },
  {
    id: 3,
    name: "Kunal Kamra",
    specialization: "Psychiatrist",
    onlineStatus: "Y",
    age: 38,
    photo: "https://randomuser.me/api/portraits/men/9.jpg",
    rating: 4.4,
    experience: 10,
    languages: ["English", "Hindi"],
    fees: 400,
  },
  {
    id: 4,
    name: "Rahul Dua",
    specialization: "Peaditrician",
    onlineStatus: "Y",
    age: 29,
    photo: "https://randomuser.me/api/portraits/men/1.jpg",
    rating: 4.2,
    experience: 6,
    languages: ["English", "Hindi", "Tamil"],
    fees: 200,
  },
  {
    id: 5,
    name: "Animesh Kumar",
    specialization: "Dentist",
    onlineStatus: "Y",
    age: 26,
    photo: "https://randomuser.me/api/portraits/men/13.jpg",
    rating: 4.0,
    experience: 7,
    languages: ["English", "Hindi"],
    fees: 450,
  },
  {
    id: 6,
    name: "Shashwat Shekhar",
    specialization: "ENT",
    onlineStatus: "Y",
    age: 34,
    photo: "https://randomuser.me/api/portraits/men/7.jpg",
    rating: 4.6,
    experience: 4,
    languages: ["English", "Hindi", "Bengali", "Marathi"],
    fees: 200,
  },
  {
    id: 7,
    name: "Utsav Kumar",
    specialization: "Opthalmologist",
    onlineStatus: "Y",
    age: 37,
    photo: "https://randomuser.me/api/portraits/men/46.jpg",
    rating: 4.4,
    experience: 14,
    languages: ["English", "Hindi", "Bengali"],
    fees: 600,
  },
  {
    id: 8,
    name: "Rohit Anand",
    specialization: "General Physician",
    onlineStatus: "Y",
    age: 36,
    photo: "https://randomuser.me/api/portraits/men/45.jpg",
    rating: 4.4,
    experience: 9,
    languages: ["English", "Hindi"],
    fees: 500,
  },
  {
    id: 9,
    name: "Akash Ghosh",
    specialization: "Dermatologist",
    onlineStatus: "Y",
    age: 33,
    photo: "https://randomuser.me/api/portraits/men/66.jpg",
    rating: 4.1,
    experience: 5,
    languages: ["English", "Hindi", "Bengali"],
    fees: 350,
  },
  {
    id: 10,
    name: "Yash Mittal",
    specialization: "ENT",
    onlineStatus: "Y",
    age: 31,
    photo: "https://randomuser.me/api/portraits/men/8.jpg",
    rating: 4.5,
    experience: 8,
    languages: ["English", "Hindi"],
    fees: 450,
  },
  {
    id: 11,
    name: "Ranveer Bisht",
    specialization: "Dentist",
    onlineStatus: "Y",
    age: 31,
    photo: "https://randomuser.me/api/portraits/men/35.jpg",
    rating: 4.6,
    experience: 10,
    languages: ["English", "Hindi"],
    fees: 500,
  },
  {
    id: 12,
    name: "Nitin Gupta",
    specialization: "Dermatologist",
    onlineStatus: "Y",
    age: 30,
    photo: "https://randomuser.me/api/portraits/men/15.jpg",
    rating: 4.3,
    experience: 6,
    languages: ["English", "Hindi", "Tamil"],
    fees: 300,
  },
  {
    id: 13,
    name: "Walter Black",
    specialization: "General Physician",
    onlineStatus: "Y",
    age: 36,
    photo: "https://randomuser.me/api/portraits/men/11.jpg",
    rating: 4.6,
    experience: 10,
    languages: ["English", "Hindi", "Marathi"],
    fees: 500,
  },
  {
    id: 14,
    name: "Jon Water",
    specialization: "Dentist",
    onlineStatus: "Y",
    age: 32,
    photo: "https://randomuser.me/api/portraits/men/79.jpg",
    rating: 4.4,
    experience: 8,
    languages: ["English", "Hindi"],
    fees: 450,
  },
  {
    id: 15,
    name: "",
    specialization: "Opthalmologist",
    onlineStatus: "Y",
    age: 35,
    photo: "https://randomuser.me/api/portraits/men/51.jpg",
    rating: 4.6,
    experience: 12,
    languages: ["English", "Hindi", "Urdu"],
    fees: 550,
  },
];
export { Doctor };
